### ISSUE TITLE
Error "60: Operation timed out" while connecting to Memcached

### ISSUE THREAD

**Issue by welcoMattic** [clickalicious/phpMemAdmin#7]
Hi!

I just install phpMemAdmin from composer and after configuring .config file, I catch this error :

```log
Fatal error: Uncaught exception 'Clickalicious\Memcached\Exception' with message 'Error "60: Operation timed out" while connecting to Memcached on host: 127.0.0.1:11211 (UUID: 9c831bd84d21932d4738344f51dec12799849ad5)' in /workspace/phpMemAdmin/vendor/clickalicious/memcached.php/lib/Clickalicious/Memcached/Client.php on line 908
```

----------------

My OS : OS X 10.10.2

PHP -v :
 ```log
PHP 5.6.5 (cli) (built: Jan 26 2015 11:37:54)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
```

Memcache client : `memcached 1.4.20`

Thanks for your work ;)

**Comment by clickalicious** [comment]
Thanks for the provided environment information - I will check for this issue as soon as I'm back home :)

**Comment by dginat** [comment]
Yes me too

**Comment by dginat** [comment]
@clickalicious @welcoMattic 
I have fixed on my fork with:
https://github.com/dginat/Memcached.php/commit/360f84bb8a53ef0257381a48b1165c626d14798a

**Comment by clickalicious** [comment]
The bug seems to be exactly at the position dginat postet in his solution. The bug itself is not a bug in phpMemAdmin - but more in Memcached.php the library used to talk to Memcached.

I tried the fix and got some more result i hoped cause it seems to fix another bug as well ;)
All tests still functional and successful.

Will release a new Memcached.php Version in a few minutes ...

**Comment by clickalicious** [comment]
Detected side effects. Will take some more time :)

**Comment by clickalicious** [comment]
I've updated Memcached.php just a few seconds ago. Try to update phpMemAdmin's composer dependencies (Memcached.php) - make sure to use >= v0.3.2

    composer update

should do the trick.

**Comment by clickalicious** [comment]
Can you please confirm :)

**Comment by welcoMattic** [comment]
Hi! Still not works on my side :/

Same error message with `clickalicious/memcached.php (v0.3.2)`

If you need more logs, tell me ;)

**Comment by welcoMattic** [comment]
Hi! 

I just fix the problem by set `self::DEFAULT_TIMEOUT` at `10`.

Don't know why it is required on my side, but it works !

**Comment by seyfer** [comment]
Need timeout setting in config. Same error

**Comment by seyfer** [comment]
Just fix it!

```
nano /var/www/nesudba2.razlet.ru/vendor/clickalicious/memcached.php/lib/Clickalicious/Memcached/Client.php
```

and set `const DEFAULT_TIMEOUT = 10`

**Comment by clickalicious** [comment]
@see https://github.com/clickalicious/phpMemAdmin/issues/6#issuecomment-74402740
