### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by kenetik** [clickalicious/phpMemAdmin#8]
I repeated receive:

    Access denied
    
    Invalid credentials.

When attempting to access to front end version. I've both altered the .config file with a new login and password, and attempted by leaving the default "admin":"pass". Results were the same in both cases.

**Comment by clickalicious** [comment]
Can you provide some more environment information:

Which client (Browser) do you use to access the page? 
What is the URL when the error message 

    Access denied

    Invalid credentials.

is shown?

Thank you for your feedback.

**Comment by kenetik** [comment]
@clickalicious Thanks for the quick reply. Currently I'm using Chrome Version 38.0.2125.101 (64-bit) and accessing via URL list:
--
http://mymemadmin.phsrvr.com/
--
Please note, that will be removed in the future for security reasons.

**Comment by clickalicious** [comment]
OK seems that you removed it while i was checking the transport headers (request/response).
Could not get enough data :) But i also wasn't able to auth with default login.

Can you provide some details about the PHP setup please

**Comment by clickalicious** [comment]
Oh DNS problems :) its back.

**Comment by kenetik** [comment]
Now that you have the URL, I'm removing it from public view, hope you understand. And more details about PHP setup: `https://gist.githubusercontent.com/kenetik/811268ba7293c2dd5773/raw/ca5407b2547ac4c027c1df902dc0728f0fa67130/gistfile1.txt` Let me know if that will suffice.

**Comment by clickalicious** [comment]
OK what i could see so far ist that some HTTPS (SSL) specific transport headers (Strict-Transport-Security ...) are sent. But not sure if they cause the trouble ... I currently can't reproduce this setup but i could test successful against my own HTTPS setup and this worked fine. 

Can't you try to install it on some other PHP configuration / machine?

**Comment by clickalicious** [comment]
Sorry but i can't reproduce this behavior in any way. 
Please let me know if i can close this issue.

Thank you.

**Comment by kenetik** [comment]
Feel free to close it, I haven't had time to test it any further.
